language: python
python:
- '3.6'
install:
- pip install .
- pip install pytest
script:
- pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: KVNjuI0sQB58rIIZWmFjzhARaXK5+rJJyYiJ53Kis89DOAqoRh4dRm+Kk1QXpQeDM1i1BnYE6hysM5JVrvIqAaNVS574ZZrYrQY3InVc4D+cr9bP422zxvx6lX366GBkiA35XTRslJHEWQWJIfNnJHmxKHiI/yVcJu96RCGL1NjEUxlpKyRt/MzdAy2aLi1otH0TdOP/nPqcCo9QAx8xKOCXHv3+pqpfPf1ss1OO6Xkli9hAKqViObXGV6SgX/8FbeV1vQbYwCXcwgZiMLtMyAUbZH7NmL7SwN1smvOsMqIwxRngQtFr11Y8zEf1acqwwVxs+IkqK/gMAEzDhQDZuyDXZIVvD94YvHBCWMA6IdnaGoSRYv9aIb7y47WbWWFEf8x/2tQWpdxqWxIq3m58ssRLuU2Jt5bVcc4o7gJ5A/7N9v0anx52LdbkD7YJdMJ2DRNxFBG77zs6EeWSBxnpJumCf67i5ydqtWtg1UtuL8cKkrjTPdv26G1Y0G8uFjo2vIjobstgDFG+IzykKR0jd0G9MNvUq53zMR3KpMhi3qtyAJsjDhL5keadjM1L9JYmyLtLPXpR1oWQYuOWYAnwj4lm2c8RnRXruGVSqo0i5+CajaEIOb5ExVqcmf0+OjQ/Q0BCW6oxCBg2K98Up9B7QkM/43S/k2UtbIkNkE02yPE=
