language: python
python:
- '3.6'
install:
- pip install .
- pip install pytest pytest-cov
script:
- py.test --cov=./
after_success:
- codecov
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
