language: python
python:
- '3.6'
install:
- pip install .
- pip install pytest
script:
- pytest
deploy:
  provider: pypi
  user: alejoe91
  on:
    tags: true
  password:
    secure: TZSGBZ+ng/CkYnm2oBv35ncJjHP8a7rcrg+yKdlLjacyoULMCzCf36EH4p4ZOdtWr09yOHSW+WFI96Q3zcuqwxkuFfPcKjRWTBnU/pZViLtNOhdUiSgMSdJw+SyJ2YPYM8xjQc1/CNu9CkEr0/0SeqfZpevBrMxuoH+G7bN49vojA9I3zB8CZ2fctFpH9qn/C+I+bhUX9vuXg5FLXCj0VDtoUFUD0lyp8mVkHiONhbPc1gKcAwGND2nx8nKxofjZs9fmpBOl0YchvrTOPl3Nwefa77+T/f0O24CAkVo1l6YjptsvMN43BFFf5v196LzKiEHWnX8FEGP9BhutwMtROJlWyQAcaUfWdsVOduw+z4PlDRRs8dd/9/vEUMzeDAo3rgqcJQ5jOUNGZoiEzGKUnGyjHdF1hGoyxTjUCUfVuc8t2L1XoYWNKKMEGocpuWxjYWgMs1J1m/ecy8upSxaFXgBhQUDVRiOu9LadiSvS5XEsQUOy3vSxJo8EXXVuVThT+VJHHfQZOqPW+owWQAAPNqJXbJ30X/YxOsiL1FSYeBT/80pktoDQU5pL61aw5hBgSuWJcNJhbO9fEnEjFQr+O3CHDbGS3AkOIBlgvLTyJdy70lYD0p2GZIV9ATQiUVPu6rhte69y6dQnKj3Cn94Bn3Z2Qk/+Njmx/1OyingHM6s=
